tools:
    external_code_coverage: true
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    environment:
        php: 8.1.2
filter:
    paths:
        - src/*
